### ISSUE TITLE
Can't monitor Tcp client connection

### ISSUE THREAD

**Issue by alinpopa** [janestreet/async#11]
Having the following code (notice the explicit monitor being added):
```
open Core.Std
open Async.Std

let con host_and_port =
  let connect () =
    let host = Host_and_port.host host_and_port in
    let port = Host_and_port.port host_and_port in
    Tcp.connect (Tcp.to_host_and_port host port)
  in
  connect () >>= (fun _ ->
    Deferred.return ("done"))

let () =
  let monitored () =
    let monitor = Monitor.create ~name:"My simple monitor" () in
    within' ~monitor (fun () -> con (Host_and_port.create "localhost" 5555)) in
  ignore (monitored ());
  never_returns (Scheduler.go ~raise_unhandled_exn:true ())
```

When the connection fails, I'm getting the following error:
```
Uncaught exception:

  ("unhandled exception"
   ((src/monitor.ml.Error_
     ((exn (Unix.Unix_error "Connection refused" connect 127.0.0.1:5555))
      (backtrace
       ("Raised by primitive operation at file \"src/unix_syscalls.ml\", line 863, characters 17-74"
        "Called from file \"src/deferred1.ml\", line 14, characters 63-68"
        "Called from file \"src/job_queue.ml\", line 160, characters 6-47"
        ""))
      (monitor
       (((name Tcp.close_sock_on_error) (here ()) (id 3)
         (has_seen_error true) (is_detached true))))))
    ((pid 3706) (thread_id 0))))

Raised at file "src/error.ml" (inlined), line 7, characters 14-30
Called from file "src/raw_scheduler.ml", line 756, characters 7-24
Called from file "test_tcp_mon.ml", line 18, characters 16-59
```
which from what I can tell, doesn't say anything about my monitor.
Is there something I'm doing wrong here?
Apologies if this is the wrong channel for addressing such questions, but I wasn't able to find a proper mailing list, or something similar to that.

Thanks.

**Comment by yminsky** [comment]
Hmm. Your monitor is included in the path, but I suspect the name doesn't show up in the monitor trace because we slimmed them down at some point to make them easier to read. Here's how you can tell it's there:

```
open Core
open Async

let con host_and_port =
  let connect () =
    let host = Host_and_port.host host_and_port in
    let port = Host_and_port.port host_and_port in
    Tcp.connect (Tcp.to_host_and_port host port)
  in
  let%bind _writer = connect () in
  Deferred.return ("done")

let () =
  let monitored () =
    let monitor = Monitor.create ~name:"My simple monitor" () in
    Monitor.detach_and_iter_errors monitor ~f:(fun exn ->
        Debug.ams [%here] "Caught it!" exn Exn.sexp_of_t;
        raise exn
      );
    let%map string = 
      Scheduler.within' ~monitor (fun () -> 
          con (Host_and_port.create ~host:"localhost" ~port:5555))
    in
    printf "%s\n" string;
  in
  don't_wait_for (monitored ());
  never_returns (Scheduler.go ~raise_unhandled_exn:true ())
```

@sliquister, do you know if there's a way of seeing monitor names in exception traces now?

**Comment by sliquister** [comment]
@yminsky I didn't remove the monitor names. Your monitor errors actually say "Caught by monitor Tcp.close_sock_on_error". But in any case, @alinpopa has teh ugly errors from before my changes.

I am not familiar with Monitor.within', but I suspect the problem is that Monitor.send_exn ignores the current execution context if the exception being sent is already a Monitor.Error_, for some reason. Ie I would expect the following:

```ocaml
Monitor.protect ~name:"a" ~finally:return (fun () ->
  Monitor.protect ~name:"b" ~finally:return) (fun () ->
    failwith "asd") 
```

to show monitor "b" only.

**Comment by sliquister** [comment]
(as a side note, it seems that jbuilder breaks the code that filters out useless stack frames, by adding these "src/" in the filenames. The stack traces should not show job_queue.ml and deferred1.ml)

**Comment by yminsky** [comment]
Odd. I guess this is just an issue with how errors are reported, rather than something about the actual structure of the monitors?

CC @diml on the jbuilder issue, and in case he understands the somewhat odd error generation here.

**Comment by alinpopa** [comment]
Thanks for the feedback, guys; sort of helped me understanding what's going on; I was a bit confused as I thought I misunderstood all the monitors concept, and I was applying it wrong.

**Comment by diml** [comment]
It's not a jbuilder issue, it's a feature. In general people want paths relative to the project root to show up in backtraces, otherwise it's hard to know what files backtraces are talking about. Technically it's not really good enough when compiling projects separately since paths might still clash but it's better than just using basenames.

My understanding is that this is what we want in our jenga rules as well, see ppx/unify-filename and the corresponding ticket. We sould probably update the async code to deal with this.

**Comment by seliopou** [comment]
Based on the discussion and its age, I think this is safe to close.
