### ISSUE TITLE
open Async.Std breaks Core code that has debugging

### ISSUE THREAD

**Issue by avsm** [janestreet/async#6]
```
# Async.Std.Printf.printf;;
- : [> `Probably_should_not_use_blocking_Core_Printf_functions_with_Async ]
```

The issue is that existing Core printfs all suddenly require decorating with `Core.Std`, which is not ideal if we just want a function or two to be Async'ed up.

**Comment by yminsky** [comment]
That's intentional.  The idea is that one should then write Core.Std.printf for that use case, to make it explicit that your working around async.  We found that people often used printf inappropriately as it was.

Also, you might want to look at the Debug module, which has useful printing functions that work nicely with ppx_here, and are simple blocking print functions.

**Comment by bmillwood** [comment]
One of the reasons why using Core.Std.printf together with Async is such a problem is that calls to Async.Std.printf and Core.Std.printf have separate buffering and can interleave output badly (AIUI, Core's blocking printf "jumps the queue" of async IO jobs)

**Comment by seliopou** [comment]
As noted, this is by design. The blocking and flushing behavior change of certain I/O-related names change depending whether you open `Async` or `Core`, and the type error is there to notify users of the change in behavior so that they don't unintentionally change that behavior.
